" Disable unused components
set nobackup
set nocompatible

"" General

filetype plugin on

" Indentation
set autoindent
filetype indent on

set backspace=indent,eol,start
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" Now we set some defaults for the editor
set history=1000                " keep 50 lines of command line history
set ruler                       " show the cursor position all the time

" Suffixes that get lower priority when doing tab completion for filenames.
" These are files we are not likely to want to edit or read.
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc,.png,.jpg

" Default clipboard register "+ (CLIPBOARD buffer in X)
set clipboard=unnamedplus

set background=dark
colorscheme hybrid_reverse
