$font_size = 48
$font_size_small = 16
$image_size = 175

general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 2
    noise = 0
}

label {
    font_family = DejaVu Sans Serif
    font_size = $font_size

    text = $TIME12
    text_align = center

    position = 0, 275
    halign = center
    valign = center
}

label {
    font_family = DejaVu Sans Serif
    font_size = $font_size_small

    text = cmd[] date "+%A, %B %d"

    position = 0, 200
    halign = center
    valign = center
}

image {
    monitor =
    path = ~/.local/bin/wm/lock.png
    size = $image_size
    rounding = -1
    border_size = 0

    halign = center
    valign = center
}

input-field {
    monitor =
    size = $image_size, $image_size

    outline_thickness = 10
    outer_color = rgba(255, 255, 255, 0.0)
    inner_color = rgba(0, 0, 0, 0.0)
    check_color = rgba(0, 0, 0, 0.0)
    fail_color = rgba(255, 0, 0, 1.0)

    font_family = DejaVu Sans Serif
    font_color = rgba(255, 255, 255, 0.9)
    placeholder_text =
    fail_text =

    hide_input = true
    rounding = -1
    fade_on_empty = false

    halign = center
    valign = center
}
