#!/bin/sh

xrdb "$XDG_CONFIG_HOME/xorg/Xresources"

# Setup display
xrandr --newmode "3000x2000_48.00" 405.25 3000 3232 3552 4104 2000 2003 2013 2058 -hsync +vsync
xrandr --addmode eDP-1 3000x2000_48.00
xrandr --output eDP-1 --mode 3000x2000_48.00 --primary

# Program starting
dunst &
redshift &

# Screensaver
xset s off
xset -dpms

## Custom keybinds

# Clear all mappings
setxkbmap -option ''

# Swap capslock with escape
setxkbmap -option caps:swapescape

exec i3
