#!/bin/sh

xrdb "$XDG_CONFIG_HOME/xorg/Xresources"

# Setup display
xrandr --newmode "3000x2000_48.00" 405.25 3000 3232 3552 4104 2000 2003 2013 2058 -hsync +vsync
xrandr --addmode eDP-1 3000x2000_48.00
xrandr --output eDP-1 --mode 3000x2000_48.00 --primary

# Set default X cursor to arrow
xsetroot -cursor_name left_ptr

# Disable screensaver
xset s off
xset -dpms

# Customize keyboard layout
inputctl.sh -k off
inputctl.sh -k on

# Turn off touchscreen
inputctl.sh -s off

# Daemon starting
dunst &
redshift &

emacs --daemon &
thunar --daemon &

sxhkd "$XDG_CONFIG_HOME/sxhkd/$WM" &
xss-lock -- "$HOME"/.scripts/wm/lock.sh &

[ "$WM" = "bspwm" ] && stalonetray &

exec $WM
